In [2]:
import numpy as np

## DataTypes And Attributes

In [3]:
# numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

## 2. Crating arrays

In [5]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [6]:
sample_array.dtype

dtype('int64')

In [7]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
ones.dtype

dtype('float64')

In [9]:
type(ones)

numpy.ndarray

In [10]:
zeros = np.zeros((2, 3))

In [11]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [13]:
random_array = np.random.a(0, 10, size=(3, 5))

In [14]:
random_array

array([[8, 8, 8, 0, 1],
       [1, 3, 8, 5, 6],
       [7, 0, 4, 3, 0]])

In [15]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.53359136, 0.43353478, 0.51003012],
       [0.03389129, 0.54061547, 0.93202838],
       [0.13773344, 0.05302474, 0.64936009],
       [0.73359405, 0.91948591, 0.97035546],
       [0.4661864 , 0.51968014, 0.09114892]])

In [16]:
random_array_3 = np.random.rand(5, 3)

In [17]:
random_array_3

array([[0.8500853 , 0.06203259, 0.98530262],
       [0.6629963 , 0.61619789, 0.93902396],
       [0.35690375, 0.660524  , 0.12852834],
       [0.36705787, 0.16022786, 0.34330405],
       [0.30104264, 0.37358948, 0.0278427 ]])

In [18]:
np.random.seed(0)
random_array_4 = np.random.random((5, 3))
random_array_4

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## 3. Viewing arrays and matrices

In [19]:
np.unique(random_array)

array([0, 1, 3, 4, 5, 6, 7, 8])

In [20]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

In [21]:
a4

array([[[[9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7],
         [0, 1, 9, 9, 0]],

        [[4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1],
         [4, 9, 8, 1, 1]],

        [[7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4],
         [4, 3, 4, 4, 8]]],


       [[[4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2],
         [4, 2, 0, 3, 2]],

        [[0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4],
         [1, 2, 9, 1, 4]],

        [[6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2],
         [3, 2, 0, 8, 8]]]])

In [22]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [28]:
a4[:1, :1, :2, :3]

array([[[[9, 4, 3],
         [5, 0, 2]]]])

## 4. Manipulating And Comparing arrays

### Arithmetic

In [29]:
a1

array([1, 2, 3])

In [31]:
ones = np.ones(3)

In [32]:
ones

array([1., 1., 1.])

In [33]:
a1 + ones

array([2., 3., 4.])

In [34]:
a1 - ones

array([0., 1., 2.])

In [35]:
a1 * ones

array([1., 2., 3.])

## Reshaping and transposing 

## 5. Sorting Arrays

In [4]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[0, 1, 2, 2, 6],
       [6, 1, 1, 8, 7],
       [4, 7, 7, 3, 7]])

In [11]:
np.sort(random_array)

array([[0, 1, 2, 2, 6],
       [1, 1, 6, 7, 8],
       [3, 4, 7, 7, 7]])

In [13]:
random_array

array([[0, 1, 2, 2, 6],
       [6, 1, 1, 8, 7],
       [4, 7, 7, 3, 7]])

In [12]:
np.argsort(random_array)

array([[0, 1, 2, 3, 4],
       [1, 2, 0, 4, 3],
       [3, 0, 1, 2, 4]])

## Practical Example

<img src="images/panda.png">

In [22]:
# Turn an image into a numpy array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [23]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [24]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)